### ISSUE TITLE
Panics on failed Cholesky decomposition

### ISSUE THREAD

**Issue by Fuuzetsu** [nestordemeure/friedrich#43]
It can happen that the Cholesky decomposition fails. A very simple way to replicate is to feed it one, 1-d sample.

Sadly when this happens, the crate throws a panic which we can't handle nicely (well, we can catch a panic but it's super nasty).

Would be nice if the failing operation could propagate up. That could let us do something like pick more parameters at random, evaluate and try again. Or change kernels and try again.

**Comment by Fuuzetsu** [comment]
I should have added a backtrace and replication. friedrich gets Option from nalgebra and uses .expect with Cholesky decomposition failed message or something like that, I'm not at the computer to check precisely.

fwiw I had the same issue even with default noise (though maybe /ess likely) so even the defaults are prone to the panic

**Comment by Fuuzetsu** [comment]
Here: https://github.com/nestordemeure/friedrich/blob/a8fff76e04674a8ac9f3a5da96258ec0fa7a66f5/src/algebra/mod.rs#L80

**Comment by nestordemeure** [comment]
One solution, the cleanest that comes to my mind, would be to implement an `unfaillible_cholesky_decomposition` method, taking the [nalgebra Cholesky constructor](https://docs.rs/nalgebra/0.29.0/src/nalgebra/linalg/cholesky.rs.html#166-201) as a basis (see also the [unchecked version](https://docs.rs/nalgebra/0.29.0/src/nalgebra/linalg/cholesky.rs.html#48-75)), that replaces zero (and negative) diagonal elements ([here](https://docs.rs/nalgebra/0.29.0/src/nalgebra/linalg/cholesky.rs.html#183)) with a given epsilon (the noise in our case).

Thus we can force our input matrix to be definite postive at a minimum performance cost and in a way that should still get us a meaningful decomposition.

**Comment by Fuuzetsu** [comment]
I wrote something but it requires a change to nalgebra because the field in `Cholesky` is private so we can't create it ourselves. It works for my use-case with a value of say 1e-8.

I tried to implement ComplexField on some `CholeskyValue` that would carry the epsilon but it turns out quite annoying: it needs `SimdValue` and so on which are hard to accommodate naively.

I guess patching nalgebra to allow to either unsafely create Cholesky or to provide version that can replace with epsilon is needed.

You can see my attempt with patched nalgebra here: https://github.com/Fuuzetsu/friedrich/commit/f43ae298408a73f0e164441ab46b9c770ee4131b

**Comment by Fuuzetsu** [comment]
I found https://github.com/dimforge/nalgebra/issues/348 which suggests that one can use LU decomposition for non-SPD matrices. I guess we could try this as a fall-back, I will try and report back.

**Comment by Fuuzetsu** [comment]
> I found [dimforge/nalgebra#348](https://github.com/dimforge/nalgebra/issues/348) which suggests that one can use LU decomposition for non-SPD matrices. I guess we could try this as a fall-back, I will try and report back.

I tried it naively and failed, I don't understand GP enough to implement this properly I think (if it's even possible with LU, I don't know).

I guess I'll go back to the "patch nalgebra" way.

**Comment by Fuuzetsu** [comment]
I'm using https://github.com/dimforge/nalgebra/pull/979 along with epsilon of 1e-8 (via modifying friedrich) and it solves the issue for me.

I guess I will send friedrich-side PR once nalgebra stuff gets merged (and released?)

**Comment by Fuuzetsu** [comment]
>You could start working on the PR once the nalgebra side is finalized+merged. I think we should wait for nalgebra to release it before merging.

I agree. I hope they release quickly. There's no change to existing API (only an addition) so it should hopefully be easy.

>(side note: I will probbaly release the current version of the code to crates.io, with your latest PRs, once I fix issue 35)

Much appreciated.

**Comment by nestordemeure** [comment]
@Fuuzetsu, nalgebra now implements [new_with_substitute](https://docs.rs/nalgebra/0.30.1/nalgebra/linalg/struct.Cholesky.html#method.new_with_substitute), would you be interested in integrating it in the current version of the code?

Otherwise, I will probbay do it by this Sunday in order to publish a new version of Friedrich on crates.io.

**Comment by Fuuzetsu** [comment]
@nestordemeure I sent a PR rebasing my long standing branch I've been using. I've been waiting for nalgebra, I guess they finally released the change.

**Comment by nestordemeure** [comment]
Great! I am tempted to use the diagonal noise as the Cholesky epsilon (one less degree of liberty for users but also one less thing to explain, one less parameter to set and its scale should make sense).

Do you see a good reason not to go in that direction?

**Comment by Fuuzetsu** [comment]
I may be completely wrong but I was under the impression that the two things do something fairly different.

As I understand it, the noise is meant to represent noise in measurements. Non-zero noise suggests that you may want to resample _exact_ same parameters that you've already sampled before as your measurement is noisy and this will build confidence (or lack thereof) in the result. In other words, when noise is positive, variance at sample points can be higher than 0. You may recall my very first change to `friedrich` at #34 which was precisely about this.

Now, Cholesky epsilon thing is _only_ used when diagonals are non-positive, usually due to numeric imprecision and some-such. This somewhat allows the decomposition to work though the results may be a bit garbage. In majority of the cases where there's nothing wrong, this epsilon does nothing.

Do you see the difference? If we set noise, this is _always_ added in. The Cholesky epsilon is only used as a last-ditch effort to salvage some poorly formed matrix and doesn't really talk about the noise in your measurements at all. If you replace `noise` and put the value in `cholesky_epsilon`, you may find that you have 0 variance at your samples unless your matrices happen to end up poorly formed at some point and the epsilon hack gets used.

I hope that makes sense. I may be wrong, let me know.

**Comment by nestordemeure** [comment]
It does make sense, thank you for the reminder on that!

I would still do two modification to the pull request:
- make the cholesky epsilon a number rather than an `Option` (since it will not be used if there is no problem, people can always set it to 0 if they want a failure when it is needed),
- give it a default value (which should be documented and modifieable) so that most people do not have to think about it (especially since it is a concept abent from other GP implementations).

The default could be something like one thousand-th of the output std (similarly to [the way the default of the noise is handled](https://github.com/nestordemeure/friedrich/blob/b68359884878b2742f64c350dc7e5cba6fddca27/src/gaussian_process/builder.rs#L71)).

**Comment by Fuuzetsu** [comment]
If we don't use an Option, we have to pick a default value and here's where the problem lies. The epsilon stuff is just a hack that goes "well, I prefer to get a slightly wrong answer than no answer at all" and I think it may be more evil to give wrong answers than to loudly crash and make user aware of the issue and try to fix their problem or _explicitly_ opt-in to the hack by picking some value. If we're producing potentially wrong answers, it felt like it should be opt-in.

>The default could be something like one thousand-th of the output std

AFAIU if epsilon is too small, the decomposition will fail either way. If it's too big, you get some ridiculous answers. Hence my reluctance to try and be clever and pick something for the user behind the scenes.

>especially since it is a concept absent from other GP implementations

I've posted few links in this thread showing bunch of GP code and Q&As that use this epsilon. What the value should be and what is acceptable seems to vary basis by basis.

----

Of course, bottom line is that if you think this should be transparent and we should pick _some_ default, I'll do it. It doesn't matter to me as we're setting the value specifically for our use-case anyway. It just seemed that it'd have been better to be explicitly opt-in, not silently-maybe-wrong and then opt-out.

**Comment by nestordemeure** [comment]
> if epsilon is too small, the decomposition will fail either way.

Is it possible? The only failure point in the Cholesky decomposition should be a negativ or zero diagonal term appearing during the decomposition but having a strictly positive cholesky-epsilon should make it strictly impossible. Am I missing something?

**Comment by nestordemeure** [comment]
> IIRC it is possible in practice if you pick a number too close to 0 as numerical issues start happening again. I don't have an example at hand. If this was not the case, one would presumably pick [MIN_POSITIVE](https://doc.rust-lang.org/std/primitive.f64.html#associatedconstant.MIN_POSITIVE).

Rereading the code, a very small value could create large values in the decomposition (when it gets inversed) leading to more substitutions in later rows so not great for the accuracy of the decomposition. So yes, we don't want to get too small (but the decomposition will always return something).

I think you point about transparency is good, lets keep it an Option type with a `None` default value. I am going to put some remarks in the PR and once they have been taken into account let's merge and publish to crates.io!

**Comment by nestordemeure** [comment]
This is now merged :)
