### ISSUE TITLE
Using `chrono` instead of `std::time`

### ISSUE THREAD

**Issue by Corwinpro** [nestordemeure/friedrich#53]
Hello! Thank you very much for this project. I really like it and would like to use it in a WASM application, but unfortunatelly `friedrich` is not quite compatible with it because of the `std::time` usage (see for example [this](https://internals.rust-lang.org/t/is-std-instant-on-webassembly-possible/18913) discussion).

I experimented a bit with your work, and apparently there is a simple change, namely: use `chrono` instead of `std::time` which fixes the issue. I tested it myself via `cargo test`, and it passes from this branch: https://github.com/Corwinpro/friedrich/pull/1/files (please ignore all styling/irrelevant formatting changes, this is my IDE).

Would you be open to add another dependency (`chrono`) to make this code WASM-compatible? Thank you very much!

**Comment by nestordemeure** [comment]
Taking a quick look, that sounds good: I would be open to a PR.

Style wise, here is a [link to my preferred rustfmt file](https://gist.github.com/nestordemeure/1ad97fed68abe46f85faebd40df4c1f4), feel free to add it to the project (I am surprised I did not already do so).

**Comment by Corwinpro** [comment]
Thanks, opened #54 - I will not mess with the formatting, but I agree there probably should be a separate PR to apply rustfmt. Thank you!
